#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

#m4 constant/polyMesh/blockMeshDict.m4 > constant/polyMesh/blockMeshDict

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#runApplication blockMesh
#runApplication surfaceFeatureExtract
#runApplication snappyHexMesh -overwrite
#runApplication topoSet
#cp 0/T.org 0/T
cp 0/C.org 0/C
#cp 0/Cstar.org 0/Cstar
cp 0/alphaT.org 0/alphaT
cp 0/alphaL.org 0/alphaL
cp 0/Dm.org 0/Dm
cp 0/Rf.org 0/Rf
cp 0/perm.org 0/perm
cp 0/beta.org 0/beta
cp 0/mu.org 0/mu
cp 0/Cim.org 0/Cim
cp 0/Cip.org 0/Cip
cp 0/Ctot.org 0/Ctot
cp 0/Klang.org 0/Klang
cp 0/Km.org 0/Km
cp 0/Ks.org 0/Ks
cp 0/aa.org 0/aa
cp 0/ad.org 0/ad
cp 0/CRmax.org 0/CRmax

#rm constant/polyMesh/boundary
#cp constant/polyMesh/boundary120z.org constant/polyMesh/boundary
runApplication setFields
runApplication `getApplication`

#runApplication decomposePar
#runParallel `getApplication` 6

runApplication reconstructPar
paraFoam -touchAll

